name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: cd into build directory
      run: cd CrashCourse_RepeatText
      
    - name: Compile
      run: g++ main.cpp
      
