name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Compile
      run: g++ CrashCourse_RepeatText/main.cpp

    - name: Run
      run: ./a.out 
      
